# Generated by Django 3.0.4 on 2021-03-31 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Org_Space',
            fields=[
                ('id', models.BigIntegerField(editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('org_space', models.BigIntegerField(editable=False, unique=True, verbose_name='org space')),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='name')),
                ('last', models.BigIntegerField(verbose_name='last value')),
            ],
            options={
                'verbose_name': 'sequence',
                'verbose_name_plural': 'sequences',
            },
        ),
    ]
