# Generated by Django 3.0.4 on 2021-03-29 18:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0002_auto_20210329_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Org_Space',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('org_space', models.BigIntegerField(editable=False, unique=True, verbose_name='org space')),
            ],
        ),
    ]
