# Generated by Django 3.0.4 on 2021-03-20 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('orgtype', models.TextField(choices=[('1', 'WORK_FLOW_MACHIN')], default='1', max_length=1)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='other_info',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reporting_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OrgMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(choices=[('1', 'ADMIN'), ('2', 'DATA_ADMIN'), ('3', 'STD')], max_length=5)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('invited_time', models.DateTimeField(null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Org')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='org',
            name='members',
            field=models.ManyToManyField(through='accounts.OrgMembers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='orgmembers',
            constraint=models.UniqueConstraint(fields=('user', 'org'), name='unique_user_per_org'),
        ),
    ]
