# Generated by Django 3.0.4 on 2021-03-22 14:58

from django.db import migrations, models
import django_s3_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210320_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(blank=True, null=True, storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='filesec-userimage'), upload_to=''),
        ),
    ]
