# Generated by Django 3.0.4 on 2021-04-02 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210402_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgmembers',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configured_members', to='accounts.Org'),
        ),
    ]
