# Generated by Django 3.0.4 on 2021-03-22 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210322_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='reporting_to',
        ),
        migrations.AddField(
            model_name='orgmembers',
            name='reporting_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporters', to=settings.AUTH_USER_MODEL),
        ),
    ]
