# Generated by Django 3.2.4 on 2021-06-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210606_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgmembers',
            name='is_verified_member',
            field=models.BooleanField(default=False),
        ),
    ]
