# Generated by Django 3.2.4 on 2021-06-22 15:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant_user_handle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('sys_ref_name', models.CharField(max_length=250)),
                ('desc', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('sys_ref_name', models.CharField(max_length=250)),
                ('desc', models.TextField(null=True)),
                ('permissions', models.ManyToManyField(to='profile_and_permission.Permission')),
                ('users', models.ManyToManyField(to='tenant_user_handle.User')),
            ],
        ),
    ]
