# Generated by Django 3.2.4 on 2021-06-24 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_user_handle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='org',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='org',
            name='accounts_org_id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='accounts_user_id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
