# Generated by Django 3.0.4 on 2020-10-14 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('licenseId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('licenseType', models.CharField(default='Free', max_length=10)),
                ('totalSpace', models.FloatField(default=50)),
                ('usedSpace', models.FloatField(default=0)),
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='License', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
