# Generated by Django 3.0.4 on 2021-06-05 21:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org', models.UUIDField(unique=True)),
                ('licenseType', models.CharField(default='TRAIL', max_length=10)),
                ('totalSpace', models.FloatField(default=500)),
                ('usedSpace', models.FloatField(default=0)),
            ],
        ),
    ]
