# Generated by Django 3.0.4 on 2021-04-03 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_org_superadmin'),
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='licenseType',
            field=models.CharField(default='TRAIL', max_length=10),
        ),
        migrations.AlterField(
            model_name='license',
            name='totalSpace',
            field=models.FloatField(default=500),
        ),
        migrations.AlterField(
            model_name='license',
            name='userId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='License', to='accounts.Org'),
        ),
    ]
