# Generated by Django 3.2.4 on 2021-06-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0003_auto_20210606_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='user_count',
            field=models.IntegerField(default=5),
        ),
    ]
