export const ACTIONS={
    FILES_INIT:"FILES_INIT",
    FILES_ADD:"FILES_ADD",
    USER_INIT:"USER_INIT",
    USER_ERROR:"USER_ERROR",
    AUTH_INIT:"AUTH_INIT",
    AUTH_REMOVE:"AUTH_REMOVE",
    EMT_STORE:"EMT_STORE",
    USER_UPDATE:"USER_UPDATE",
    FILES_DEL:"FILES_DEL",
    LICENSE_INIT:"LICENSE_INIT"
  }